version: "3"
services:
  web:
    build: ./
    image: "theophile/cos-api-gui"
    user: "node"
    ports:
      - '3000:3000'
      - '3001:3001'
    command: "npm run start-dev"
  mongodb:
    image: mongo
    ports:
      - '27017:27017'