version: 2
jobs:
  build:
    docker:
      # primary image
      - image: circleci/node:8.6.0
        name: api-container
      #db for the system
      - image: circleci/mongo:3.4.4
        name: mongodb
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install --only=production

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      #deploy
      - run: npm run startApi & sleep 3 && API_URL=http://localhost:3001/api npm run test
      # run tests!
general:
  branches:
    only:
      - CI
